a = input('digite algo: ')
print('0 tipo primitivo desse valor é:', type(a))
print('só tem espaços', a.isspace())
print('é um numero?', a.isnumeric())
print('é alfabetico?', a.isalpha())
print('é alfanumero?', a.isalnum())
print('está em maiusculas?', a.isupper())
print('está em minusculas?', a.islower())
print('está capitalizada?', a.istitle())
print('')
